name: RNA SEQ CI

on:
  push:
    branches:
      -main
jobs:
test-pipeline:
runs-on: ubuntu-latest

steps:
  -name: checkout repository 
   uses: actions/checkout@v4
  
   -name: setup java 
    uses: actions/setup-java@v4
     with:
      distribution: 'temurin'
      java-version: '17'
  
  -name: setup Nextflow
   uses: nf-core/setup-Nextflow@v2
    with: 
      version: latest

name: Verify Nextflow 
run: Nextflow -version
