name: RNAseq CI

on:
  push:
    branches:
      - main

jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: latest

      - name: Check Nextflow version
        run: nextflow -version